export * from '@/components/templates/addStudent/index';
export * from '@/components/templates/editStudent/index';
export * from '@/components/templates/listStudent/index';
export * from '@/components/templates/listIntitute/index';
export * from '@/components/templates/addIntitute/index';
export * from '@/components/templates/editInstitute/index';
export * from '@/components/templates/addPayment/index';
export * from '@/components/templates/listPayment/index';
export * from '@/components/templates/viewPaymentById/index';